// constants/index.ts
import { Product } from '../interfaces';
import { CategoryKey } from '../interfaces';


export const UI_TEXT = {
  BRAND_NAME: 'e-spaxe',
  href: '/',
  WELCOME_MESSAGE: 'Browse the latest fashion for men & women!',
  BUY_NOW: 'Buy Now',
  VIEW_DETAILS: 'View Details',
  ALL_CATEGORIES: 'All Categories',
  LOADING: 'Loading...',
  ERROR: 'Something went wrong. Please try again.',
  SEARCH: 'Search',
  WISHLIST: 'Wishlist',
  CART: 'Cart',
  ACCOUNT: 'Account',
  NEW_ARRIVALS: 'New Arrivals',
  OUR_PRODUCTS: 'Our Products',
  QUICK_ADD: 'Quick Add',
  QUICK_VIEW: 'Quick View',
  VIEW_ALL: 'View All',
  FILTERS: 'Filters',
  CATEGORY: 'Category',
  MATERIAL: 'Material',
  PRICE_RANGE: 'Price Range',
  NO_PRODUCTS: 'No products found matching your criteria.',
  ITEMS: 'items',
  SUBSCRIBE: 'Subscribe',
  FOOTER_COMPANY: 'e-spaxe',
  FOOTER_EMAIL: 'contact@e-spaxe.com',
  FOOTER_PHONE: '+(123) 456-7890',
  FOOTER_ADDRESS: '1093 Hood Avenue, CA',
  FOOTER_HOURS: 'All Day: 9:00AM - 22:00PM',
  FOOTER_COPYRIGHT: '© 2025 e-spaxe. All rights reserved.',
  ADD_TO_CART: 'Add to Cart',
  ADD_TO_WISHLIST: 'Add to Wishlist',
  REMOVE_FROM_WISHLIST: 'Remove from Wishlist',
  SHARE: 'Share',
  TOTAL: 'Total',
  SHIPPING: 'Shipping',
  SHIPPING_CALCULATED_AT_CHECKOUT: 'Shipping & taxes calculated at checkout',
  FREE_SHIPPING: 'Free Shipping',
  SPEND: 'Spend',
  FOR: 'for',
  CONTINUE_SHOPPING: 'Continue Shopping',
  VIEW_CART: 'View Cart',
  PROCEED_TO_CHECKOUT: 'Proceed to Checkout',
  FREE_SHIPPING_ELIGIBLE: 'Free shipping for any orders above $1,000.00',
  PRODUCT: 'Product',
  PRICE: 'Price',
  QTY: 'Qty',
  HOME: 'Home',
};

export const NAV_ITEMS = [
  { label: 'Home', href: '/' },
  {
    label: 'Men',
    hasDropdown: true,
    dropdownContent: [
      {
        title: 'Clothing',
        links: ['Shirts', 'T-Shirts', 'Jeans', 'Jackets', 'Suits', 'Activewear'],
      },
      {
        title: 'Accessories',
        links: ['Watches', 'Jewelry', 'Sunglasses', 'Hats', 'Belts'],
      },
      {
        title: 'Collections',
        links: ['New Arrivals', 'Best Sellers', 'Seasonal Picks', 'Essentials'],
      },
    ],
  },
  {
    label: 'Women',
    hasDropdown: true,
    dropdownContent: [
      {
        title: 'Clothing',
        links: ['Dresses', 'Tops', 'Pants', 'Skirts', 'Outerwear', 'Activewear'],
      },
      {
        title: 'Accessories',
        links: ['Bags', 'Shoes', 'Jewelry', 'Sunglasses', 'Hats'],
      },
      {
        title: 'Collections',
        links: ['New Arrivals', 'Best Sellers', 'Seasonal Collection', 'Essentials'],
      },
    ],
  },
  {
    label: 'Accessories',
    hasDropdown: true,
    dropdownContent: [
      {
        title: 'For Men',
        links: ['Watches', 'Jewelry', 'Sunglasses', 'Hats', 'Belts'],
      },
      {
        title: 'For Women',
        links: ['Bags', 'Shoes', 'Jewelry', 'Sunglasses', 'Hats'],
      },
      {
        title: 'Unisex',
        links: ['Watches', 'Sunglasses', 'Backpacks', 'Wallets'],
      },
    ],
  },
  // { 
  //   label: 'Info', 
  //   hasDropdown: true,
  //   dropdownContent: [
  //     {
  //       title: 'Customer',
  //       links: ['Account', 'Login', 'Register', 'Wishlist', 'Checkout'],
  //     },
  //     {
  //       title: 'Help',
  //       links: ['About Us', 'Contact', 'FAQ', 'Size Guide', 'Shipping & Returns'],
  //     },
  //   ],
  // },
];

export const HERO_CONTENT = {
  tagline: 'STYLE FOR EVERYONE',
  title: 'Men & Women Fashion',
  subtitle: 'New season arrivals for all',
  description:
    'Explore the latest trends and timeless staples across our men’s and women’s collections.',
  buttonText: 'Shop All',
};

export const PRODUCT_CATEGORIES = [
  // Gender-neutral
  'New Arrivals',
  'Best Sellers',
  'Seasonal Picks',
  'Essentials',
  // Women
  'womens-dresses',
  'womens-tops',
  'womens-pants',
  'womens-skirts',
  'womens-outerwear',
  'womens-activewear',
  // Men
  'mens-shirts',
  'mens-t-shirts',
  'mens-jeans',
  'mens-jackets',
  'mens-suits',
  'mens-activewear',
  // Accessories
  'bags',
  'shoes',
  'jewelery',
  'watches',
  'sunglasses',
  'hats',
];

export const PRODUCT_STYLES = [
  'Casual',
  'Formal',
  'Workwear',
  'Sporty',
  'Lounge',
  'Trendy',
  'Minimalist',
  'Vintage',
];

export const PRODUCT_OCCASIONS = [
  'Everyday',
  'Weekend',
  'Vacation',
  'Weddings',
  'Holiday Parties',
  'Gifting',
];

export const FILTER_CATEGORIES = [
  'womens-dresses',
  'womens-tops',
  'mens-shirts',
  'mens-t-shirts',
  'jewelery',
  'bags',
  'shoes',
];

export const FILTER_MATERIALS = [
  'cotton',
  'polyester',
  'leather',
  'denim',
  'silk',
  'wool',
  'gold',
  'silver',
  'platinum',
];

export const FILTER_PRICE_RANGES = [
  { label: 'Under $50', min: 0, max: 50 },
  { label: '$50 - $100', min: 50, max: 100 },
  { label: '$100 - $200', min: 100, max: 200 },
  { label: 'Over $200', min: 200, max: Infinity },
];

export const CATEGORIES_META = [
  { id: 1, name: 'Necklaces', slug: 'jewelery' },
  { id: 2, name: 'Earrings', slug: 'earrings' },
  { id: 3, name: 'Bracelets', slug: 'bracelets' },
  { id: 4, name: 'Rings', slug: 'rings' },
];

export const CATEGORIES = [
  {
    id: 1,
    name: 'Jewelry',
    slug: 'jewelery',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROot05_q-RCSVhTkSQjZ5YTrncdbZCUB6n5A&s?w=400&h=500&fit=crop&crop=center',
  },
  {
    id: 2,
    name: 'Dresses',
    slug: 'womens-dresses',
    image: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=400&h=500&fit=crop&crop=center',
  },
  {
    id: 3,
    name: 'Shirts',
    slug: 'mens-shirts',
    image: 'https://images.unsplash.com/photo-1596755032439-0b297c8a371e?w=400&h=500&fit=crop&crop=center',
  },
  {
    id: 4,
    name: 'T-Shirts',
    slug: 'mens-t-shirts',
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&h=500&fit=crop&crop=center',
  },
  {
    id: 5,
    name: 'Bags',
    slug: 'bags',
    image: 'https://images.unsplash.com/photo-1590451999253-6113b6473b64?w=400&h=500&fit=crop&crop=center',
  },
  {
    id: 6,
    name: 'Shoes',
    slug: 'shoes',
    image: 'https://images.unsplash.com/photo-1516478177764-9fe567e9777d?w=400&h=500&fit=crop&crop=center',
  },
];

export const CATEGORY_SUBCATEGORIES: Record<CategoryKey, string[]> = {
  Jewelry: ['Necklaces', 'Earrings', 'Bracelets', 'Rings', 'Watches', 'Anklets'],
  'womens-dresses': ['Casual Dresses', 'Evening Dresses', 'Maxi Dresses', 'Mini Dresses', 'Cocktail Dresses'],
  'womens-tops': ['Blouses', 'T-Shirts', 'Tank Tops', 'Sweaters', 'Cardigans'],
  'mens-shirts': ['Dress Shirts', 'Casual Shirts', 'Polo Shirts', 'Henley Shirts'],
  'mens-t-shirts': ['Graphic Tees', 'Plain Tees', 'V-Neck', 'Crew Neck', 'Long Sleeve'],
  'Girls Clothing': ['T-Shirts', 'Dresses', 'Skirts', 'Pants', 'Sweaters'],
  'Boys Clothing': ['T-Shirts', 'Shorts', 'Pants', 'Sweaters', 'Jackets'],
  bags: ['Handbags', 'Backpacks', 'Crossbody', 'Tote Bags', 'Clutches'],
  shoes: ['Sneakers', 'Boots', 'Flats', 'Heels', 'Sandals'],
};

export const CATEGORY_MATERIALS: Record<CategoryKey, string[]> = {
  Jewelry: ['gold', 'silver', 'platinum', 'rose-gold', 'stainless-steel', 'titanium'],
  'womens-dresses': ['cotton', 'polyester', 'silk', 'chiffon', 'lace', 'satin'],
  'womens-tops': ['cotton', 'polyester', 'silk', 'wool', 'cashmere', 'linen'],
  'mens-shirts': ['cotton', 'linen', 'polyester', 'silk', 'oxford-cloth'],
  'mens-t-shirts': ['cotton', 'polyester', 'bamboo', 'modal', 'tri-blend'],
  bags: ['leather', 'canvas', 'nylon', 'polyester', 'vegan-leather'],
  'Girls Clothing': ['cotton', 'polyester', 'denim', 'jersey', 'knit'],
  'Boys Clothing': ['cotton', 'polyester', 'denim', 'jersey', 'knit'],
  shoes: ['leather', 'canvas', 'rubber', 'synthetic', 'suede'],
};

export const FOOTER_SECTIONS = [
  {
    title: 'My Account',
    links: [
      { label: 'Login/Register', href: '/account' },
      { label: 'Wishlist', href: '/wishlist' },
      { label: 'Track Your Orders', href: '/orders' },
      { label: 'Checkout', href: '/checkout' },
    ],
  },
  {
    title: 'Our Policies',
    links: [
      { label: 'Shipping & Delivery', href: '/shipping' },
      { label: 'Returns Policy', href: '/returns' },
      { label: 'Terms & Conditions', href: '/terms' },
      { label: 'Privacy Policy', href: '/privacy' },
    ],
  },
  {
    title: 'Customer Care',
    links: [
      { label: 'FAQs', href: '/faq' },
      { label: 'Terms of Service', href: '/terms' },
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Gift Card', href: '/gift-card' },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // New Arrivals
  {
    id: '1',
    name: 'Floral Print Midi Dress',
    price: 79.99,
    originalPrice: 99.99, 
    image: 'https://zephansandco.com/wp-content/uploads/2024/04/4B7A8635-jpg.webp?w=400&h=500&fit=crop',
    rating: 4.7,
    reviews: 820,
    isWishlisted: false,
    category: 'New Arrivals',
    material: 'cotton',
    description: 'A vibrant floral midi dress, perfect for spring and summer outings.',
    inStock: true,
    features: ['Breathable cotton fabric', 'A-line silhouette', 'Side pockets', 'Back zipper closure'],
    specifications: { Material: '100% Cotton', Length: 'Midi', Care: 'Machine Wash' },
  },
  {
    id: '2',
    name: 'Smart Casual Blazer',
    price: 149.99,
    originalPrice: 199.99,
    image: 'https://img.freepik.com/free-photo/side-view-handsome-man-looking-away-outside_23-2148448870.jpg?w=400&h=500&fit=crop&crop=center',
    rating: 4.8,
    reviews: 650,
    isWishlisted: true,
    category: 'New Arrivals',
    material: 'wool',
    description: 'A versatile blazer for both office and evening wear, crafted from premium wool.',
    inStock: true,
    features: ['Single-breasted design', 'Notched lapel', 'Two-button closure', 'Side vents'],
    specifications: { Material: '80% Wool, 20% Polyester', Fit: 'Slim', Care: 'Dry Clean' },
    relatedProducts: ['9', '15', '21'],
  },
  {
    id: '3',
    name: 'Leather Crossbody Bag',
    price: 129.99,
    originalPrice: 159.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXzsgbrfL9hJxoUWpgnDb6vZq1Jg8W9tu6Dw&s?w=300&h=500&fit=crop&crop=center',
    rating: 4.6,
    reviews: 430,
    isWishlisted: false,
    category: 'New Arrivals',
    material: 'leather',
    description: 'A chic leather crossbody bag, ideal for everyday essentials.',
    inStock: true,
    features: ['Adjustable strap', 'Magnetic closure', 'Interior zip pocket', 'Genuine leather'],
    specifications: { Material: 'Genuine Leather', Dimensions: '10" W x 7" H x 3" D', Color: 'Black' },
    relatedProducts: ['10', '16', '22'],
  },


  // Best Sellers
  {
    id: '4',
    name: 'Classic White T-Shirt',
    price: 29.99,
    originalPrice: 39.99,
    image: 'https://img.freepik.com/premium-photo/unisex-tshirt-png-mockup-casual-fashion-transparent-design_53876-1017455.jpg?w=400&h=500&fit=crop&crop=center',
    rating: 4.9,
    reviews: 2450,
    isWishlisted: true,
    category: 'Best Sellers',
    material: 'cotton',
    description: 'A timeless white crew neck t-shirt, a wardrobe essential for all seasons.',
    inStock: true,
    features: ['Soft cotton blend', 'Crew neck', 'Regular fit', 'Pre-shrunk'],
    specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
    relatedProducts: ['12', '18', '24'],
  },
  {
    id: '5',
    name: 'Gold Hoop Earrings',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjeWUu34jVmjVkZoLq3Yh5NiK6wmhkoE9oMQ&s?w=400&h=500&fit=crop&crop=center',
    rating: 4.8,
    reviews: 980,
    isWishlisted: false,
    category: 'Best Sellers',
    material: 'gold',
    description: 'Elegant gold hoop earrings, perfect for adding a touch of glamour.',
    inStock: true,
    features: ['14K Gold Plated', 'Lightweight', 'Secure clasp', '30mm diameter'],
    specifications: { Material: '14K Gold Plated', Diameter: '30mm', Weight: '5g' },
    relatedProducts: ['1', '7', '13'],
  },

  {
    id: '6',
    name: 'Denim Jacket',
    price: 99.99,
    originalPrice: 129.99,
    image: 'https://img.freepik.com/free-photo/woman-wearing-jeans-jacket-mockup_53876-96253.jpg?w=400&h=500&fit=crop&crop=center',
    images: [
      'https://images.unsplash.com/photo-1525171254930-643fc83d3c66?w=600&h=600&fit=crop',
    ],
    rating: 4.7,
    reviews: 1200,
    isWishlisted: true,
    category: 'Best Sellers',
    material: 'denim',
    description: 'A classic denim jacket with a modern slim fit, perfect for layering.',
    inStock: true,
    features: ['100% Cotton Denim', 'Button-front closure', 'Chest pockets', 'Distressed finish'],
    specifications: { Material: '100% Cotton', Fit: 'Slim', Care: 'Machine Wash' },
    relatedProducts: ['15', '21', '27'],
  },

  // Seasonal Picks
  {
    id: '7',
    name: 'Wool Blend Coat',
    price: 199.99,
    originalPrice: 249.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfU7yAqzTiPAZQs_PPJ9mq6mLTjb7r_ru96g&s?w=400&h=500&fit=crop&crop=center',
    rating: 4.8,
    reviews: 670,
    isWishlisted: false,
    category: 'Seasonal Picks',
    material: 'wool',
    description: 'A warm wool blend coat, ideal for fall and winter wardrobes.',
    inStock: true,
    features: ['Wool blend fabric', 'Double-breasted', 'Side pockets', 'Fully lined'],
    specifications: { Material: '70% Wool, 30% Polyester', Length: 'Knee-length', Care: 'Dry Clean' },
    relatedProducts: ['2', '9', '15'],
  },
  {
    id: '8',
    name: 'Suede Ankle Boots',
    price: 139.99,
    originalPrice: 179.99,
    image: 'https://images.unsplash.com/photo-1543168256-418811576f69?w=400&h=500&fit=crop&crop=center',
    images: [
      'https://images.unsplash.com/photo-1543168256-418811576f69?w=600&h=600&fit=crop',
    ],
    rating: 4.6,
    reviews: 540,
    isWishlisted: true,
    category: 'Seasonal Picks',
    material: 'suede',
    description: 'Stylish suede ankle boots, perfect for the autumn season.',
    inStock: true,
    features: ['Genuine suede', 'Side zipper', 'Cushioned insole', '2-inch heel'],
    specifications: { Material: 'Suede', HeelHeight: '2 inches', Care: 'Suede Cleaner' },
    relatedProducts: ['16', '22', '28'],
  },
  {
    id: '9',
    name: 'Cable Knit Sweater',
    price: 69.99,
    originalPrice: 89.99,
    image: 'https://images.unsplash.com/photo-1576871337622-98d48e1f3678?w=400&h=500&fit=crop&crop=center',
    images: [
      'https://images.unsplash.com/photo-1576871337622-98d48e1f3678?w=600&h=600&fit=crop',
    ],
    rating: 4.7,
    reviews: 890,
    isWishlisted: false,
    category: 'Seasonal Picks',
    material: 'wool',
    description: 'A cozy cable knit sweater for chilly days, made from soft wool.',
    inStock: true,
    features: ['Soft wool blend', 'Crew neck', 'Ribbed cuffs', 'Regular fit'],
    specifications: { Material: '60% Wool, 40% Acrylic', Fit: 'Regular', Care: 'Hand Wash' },
    relatedProducts: ['7', '15', '21'],
  },

  // Essentials
  {
    id: '10',
    name: 'Black Leather Belt',
    price: 49.99,
    originalPrice: 59.99,
    image: 'https://images.unsplash.com/photo-1594233396712-7d1634b7c6e5?w=400&h=500&fit=crop&crop=center',
    images: [
      'https://images.unsplash.com/photo-1594233396712-7d1634b7c6e5?w=600&h=600&fit=crop',
    ],
    rating: 4.5,
    reviews: 780,
    isWishlisted: false,
    category: 'Essentials',
    material: 'leather',
    description: 'A timeless black leather belt, a must-have for any wardrobe.',
    inStock: true,
    features: ['Genuine leather', 'Silver buckle', 'Adjustable fit', 'Durable stitching'],
    specifications: { Material: 'Genuine Leather', Width: '1.5 inches', Length: 'Adjustable' },
    relatedProducts: ['12', '18', '24'],
  },
  {
    id: '11',
    name: 'Floral Print Midi Dress',
    price: 79.99,
    originalPrice: 99.99,
    image: 'https://zephansandco.com/wp-content/uploads/2024/04/4B7A8635-jpg.webp?w=400&h=500&fit=crop',
    rating: 4.7,
    reviews: 820,
    isWishlisted: false,
    category: 'Women',
    subCategory: "Clothing",
    collections: 'New Arrivals',
    product: 'Dresses',
    material: 'cotton',
    description: 'A vibrant floral midi dress, perfect for spring and summer outings.',
    inStock: true,
    features: ['Breathable cotton fabric', 'A-line silhouette', 'Side pockets', 'Back zipper closure'],
    specifications: { Material: '100% Cotton', Length: 'Midi', Care: 'Machine Wash' },
  },
  {
    id: '12',
    name: 'Smart Casual Blazer',
    price: 149.99,
    originalPrice: 199.99,
    image: 'https://img.freepik.com/free-photo/side-view-handsome-man-looking-away-outside_23-2148448870.jpg?w=400&h=500&fit=crop&crop=center',
    rating: 4.8,
    reviews: 650,
    isWishlisted: true,
    category: 'Men',
    subCategory: "Clothing",
    collections: 'New Arrivals',
    product: 'Jackets',
    material: 'wool',
    description: 'A versatile blazer for both office and evening wear, crafted from premium wool.',
    inStock: true,
    features: ['Single-breasted design', 'Notched lapel', 'Two-button closure', 'Side vents'],
    specifications: { Material: '80% Wool, 20% Polyester', Fit: 'Slim', Care: 'Dry Clean' },
    relatedProducts: ['9', '15', '21'],
  },
  {
    id: '13',
    name: 'Leather Crossbody Bag',
    price: 129.99,
    originalPrice: 159.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXzsgbrfL9hJxoUWpgnDb6vZq1Jg8W9tu6Dw&s?w=300&h=500&fit=crop&crop=center',
    rating: 4.6,
    reviews: 430,
    isWishlisted: false,
    category: 'New Arrivals',
    material: 'leather',
    description: 'A chic leather crossbody bag, ideal for everyday essentials.',
    inStock: true,
    features: ['Adjustable strap', 'Magnetic closure', 'Interior zip pocket', 'Genuine leather'],
    specifications: { Material: 'Genuine Leather', Dimensions: '10" W x 7" H x 3" D', Color: 'Black' },
    relatedProducts: ['10', '16', '22'],
  },
  {
    id: '14',
    name: 'Classic White T-Shirt',
    price: 29.99,
    originalPrice: 39.99,
    image: 'https://img.freepik.com/premium-photo/unisex-tshirt-png-mockup-casual-fashion-transparent-design_53876-1017455.jpg?w=400&h=500&fit=crop&crop=center',
    rating: 4.9,
    reviews: 2450,
    isWishlisted: true,
    material: 'cotton',
    category: 'Men',
  subCategory: 'Clothing',
  product: 'T-Shirts',
    description: 'A timeless white crew neck t-shirt, a wardrobe essential for all seasons.',
    inStock: true,
    features: ['Soft cotton blend', 'Crew neck', 'Regular fit', 'Pre-shrunk'],
    specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
    relatedProducts: ['12', '18', '24'],
  },
  {
    id: '15',
    name: 'Gold Hoop Earrings',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjeWUu34jVmjVkZoLq3Yh5NiK6wmhkoE9oMQ&s?w=400&h=500&fit=crop&crop=center',
    rating: 4.8,
    reviews: 980,
    isWishlisted: false,
    category: 'Best Sellers',
    material: 'gold',
    description: 'Elegant gold hoop earrings, perfect for adding a touch of glamour.',
    inStock: true,
    features: ['14K Gold Plated', 'Lightweight', 'Secure clasp', '30mm diameter'],
    specifications: { Material: '14K Gold Plated', Diameter: '30mm', Weight: '5g' },
    relatedProducts: ['1', '7', '13'],
  },
  {
  id: '16',
  name: 'Men’s Graphic T-Shirt',
  price: 34.99,
  originalPrice: 44.99,
  image: 'https://img.freepik.com/premium-photo/unisex-tshirt-png-mockup-casual-fashion-transparent-design_53876-1017455.jpg?w=400&h=500&fit=crop&crop=center',
  rating: 4.6,
  reviews: 1200,
  isWishlisted: false,
  category: 'Men',
  subCategory: 'Clothing',
  product: 'T-Shirts',
  material: 'cotton',
  description: 'A trendy graphic T-shirt for men.',
  inStock: true,
  features: ['100% Cotton', 'Crew neck', 'Printed design'],
  specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
}
]
//   {
//     id: '11',
//     name: 'White Sneakers',
//     price: 69.99,
//     originalPrice: 89.99,
//     image: 'https://images.unsplash.com/photo-1516478177764-9fe567e9777d?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1516478177764-9fe567e9777d?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 2100,
//     isWishlisted: true,
//     category: 'Essentials',
//     material: 'canvas',
//     description: 'Versatile white canvas sneakers, perfect for casual looks.',
//     inStock: true,
//     features: ['Canvas upper', 'Rubber sole', 'Lace-up closure', 'Breathable lining'],
//     specifications: { Material: 'Canvas', Outsole: 'Rubber', Color: 'White' },
//     relatedProducts: ['10', '16', '22'],
//   },
//   {
//     id: '12',
//     name: 'Basic Cotton Tee',
//     price: 24.99,
//     originalPrice: 34.99,
//     image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 1500,
//     isWishlisted: false,
//     category: 'Essentials',
//     material: 'cotton',
//     description: 'A soft and comfortable cotton t-shirt, ideal for everyday wear.',
//     inStock: true,
//     features: ['100% Cotton', 'Crew neck', 'Short sleeves', 'Pre-shrunk'],
//     specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['4', '18', '24'],
//   },

//   // womens-dresses
//   {
//     id: '13',
//     name: 'Sequin Evening Dress',
//     price: 159.99,
//     originalPrice: 199.99,
//     image: 'https://images.unsplash.com/photo-1590245613023-5a5298539611?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1590245613023-5a5298539611?w=600&h=600&fit=crop',
//     ],
//     rating: 4.9,
//     reviews: 420,
//     isWishlisted: true,
//     category: 'Evening Dresses',
//     material: 'sequin',
//     description: 'A glamorous sequin evening dress, perfect for parties and special occasions.',
//     inStock: true,
//     features: ['All-over sequins', 'V-neckline', 'Bodycon fit', 'Hidden zipper'],
//     specifications: { Material: 'Polyester, Sequin', Length: 'Mini', Care: 'Dry Clean' },
//     relatedProducts: ['1', '6', '14'],
//   },
//   {
//     id: '14',
//     name: 'Maxi Wrap Dress',
//     price: 89.99,
//     originalPrice: 109.99,
//     image: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 750,
//     isWishlisted: false,
//     category: 'Maxi Dresses',
//     material: 'chiffon',
//     description: 'A flowy chiffon maxi dress with a wrap front, ideal for summer events.',
//     inStock: true,
//     features: ['Chiffon fabric', 'Wrap front', 'Adjustable tie waist', 'Sleeveless'],
//     specifications: { Material: '100% Chiffon', Length: 'Maxi', Care: 'Hand Wash' },
//     relatedProducts: ['1', '13', '15'],
//   },
//   {
//     id: '15',
//     name: 'Cocktail A-Line Dress',
//     price: 129.99,
//     originalPrice: 159.99,
//     image: 'https://images.unsplash.com/photo-1541695434934-7c316712399e?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1541695434934-7c316712399e?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 600,
//     isWishlisted: true,
//     category: 'Cocktail Dresses',
//     material: 'satin',
//     description: 'A sleek satin A-line dress, perfect for cocktail parties and evening wear.',
//     inStock: true,
//     features: ['Satin finish', 'A-line silhouette', 'Sleeveless', 'Back zipper'],
//     specifications: { Material: '100% Satin', Length: 'Knee-length', Care: 'Dry Clean' },
//     relatedProducts: ['13', '14', '16'],
//   },

//   // womens-tops
//   {
//     id: '16',
//     name: 'Silk Blouse',
//     price: 99.99,
//     originalPrice: 129.99,
//     image: 'https://images.unsplash.com/photo-1589465885857-add72199e46a?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1589465885857-add72199e46a?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 680,
//     isWishlisted: false,
//     category: 'Blouses',
//     material: 'silk',
//     description: 'A luxurious silk blouse with a soft drape, perfect for work or evening wear.',
//     inStock: true,
//     features: ['100% Mulberry Silk', 'Button-front', 'Long sleeves', 'Regular fit'],
//     specifications: { Material: '100% Silk', Fit: 'Regular', Care: 'Dry Clean' },
//     relatedProducts: ['14', '15', '17'],
//   },
//   {
//     id: '17',
//     name: 'Cashmere Sweater',
//     price: 119.99,
//     originalPrice: 149.99,
//     image: 'https://images.unsplash.com/photo-1576871337622-98d48e1f3678?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1576871337622-98d48e1f3678?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 720,
//     isWishlisted: true,
//     category: 'Sweaters',
//     material: 'cashmere',
//     description: 'A soft cashmere sweater, ideal for cozy fall and winter days.',
//     inStock: true,
//     features: ['100% Cashmere', 'Crew neck', 'Ribbed cuffs', 'Lightweight'],
//     specifications: { Material: '100% Cashmere', Fit: 'Regular', Care: 'Hand Wash' },
//     relatedProducts: ['9', '16', '18'],
//   },
//   {
//     id: '18',
//     name: 'Cotton Tank Top',
//     price: 29.99,
//     originalPrice: 39.99,
//     image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 890,
//     isWishlisted: false,
//     category: 'Tank Tops',
//     material: 'cotton',
//     description: 'A versatile cotton tank top, great for layering or wearing alone.',
//     inStock: true,
//     features: ['100% Cotton', 'Scoop neck', 'Sleeveless', 'Breathable fabric'],
//     specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['12', '16', '17'],
//   },

//   // womens-pants
//   {
//     id: '19',
//     name: 'High-Waisted Leggings',
//     price: 49.99,
//     originalPrice: 69.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 950,
//     isWishlisted: true,
//     category: 'womens-pants',
//     material: 'polyester',
//     description: 'Comfortable high-waisted leggings, perfect for workouts or casual wear.',
//     inStock: true,
//     features: ['Stretch polyester', 'High-waisted', 'Moisture-wicking', 'Side pocket'],
//     specifications: { Material: '90% Polyester, 10% Spandex', Fit: 'Fitted', Care: 'Machine Wash' },
//     relatedProducts: ['20', '21', '30'],
//   },
//   {
//     id: '20',
//     name: 'Tailored Trousers',
//     price: 89.99,
//     originalPrice: 109.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 620,
//     isWishlisted: false,
//     category: 'womens-pants',
//     material: 'wool',
//     description: 'Elegant tailored trousers, ideal for professional settings.',
//     inStock: true,
//     features: ['Wool blend', 'Straight leg', 'Front pleats', 'Belt loops'],
//     specifications: { Material: '70% Wool, 30% Polyester', Fit: 'Regular', Care: 'Dry Clean' },
//     relatedProducts: ['19', '21', '30'],
//   },
//   {
//     id: '21',
//     name: 'Cropped Chinos',
//     price: 59.99,
//     originalPrice: 79.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 780,
//     isWishlisted: true,
//     category: 'womens-pants',
//     material: 'cotton',
//     description: 'Casual cropped chinos, perfect for a relaxed weekend look.',
//     inStock: true,
//     features: ['100% Cotton', 'Cropped length', 'Side pockets', 'Slim fit'],
//     specifications: { Material: '100% Cotton', Length: 'Cropped', Care: 'Machine Wash' },
//     relatedProducts: ['19', '20', '30'],
//   },

//   // womens-skirts
//   {
//     id: '22',
//     name: 'Pleated Midi Skirt',
//     price: 69.99,
//     originalPrice: 89.99,
//     image: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 560,
//     isWishlisted: false,
//     category: 'womens-skirts',
//     material: 'polyester',
//     description: 'A flowy pleated midi skirt, perfect for both casual and dressy occasions.',
//     inStock: true,
//     features: ['Polyester blend', 'Pleated design', 'Elastic waist', 'Midi length'],
//     specifications: { Material: '100% Polyester', Length: 'Midi', Care: 'Machine Wash' },
//     relatedProducts: ['14', '15', '23'],
//   },
//   {
//     id: '23',
//     name: 'Denim Mini Skirt',
//     price: 49.99,
//     originalPrice: 59.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 820,
//     isWishlisted: true,
//     category: 'womens-skirts',
//     material: 'denim',
//     description: 'A classic denim mini skirt with a modern twist, perfect for casual outings.',
//     inStock: true,
//     features: ['100% Cotton Denim', 'A-line shape', 'Front pockets', 'Button closure'],
//     specifications: { Material: '100% Cotton', Length: 'Mini', Care: 'Machine Wash' },
//     relatedProducts: ['6', '22', '24'],
//   },

//   // womens-outerwear
//   {
//     id: '24',
//     name: 'Faux Fur Coat',
//     price: 199.99,
//     originalPrice: 249.99,
//     image: 'https://images.unsplash.com/photo-1544027993-7ad4f6a7a3a0?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1544027993-7ad4f6a7a3a0?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 430,
//     isWishlisted: true,
//     category: 'womens-outerwear',
//     material: 'polyester',
//     description: 'A luxurious faux fur coat, perfect for staying warm and stylish in winter.',
//     inStock: true,
//     features: ['Faux fur', 'Oversized fit', 'Side pockets', 'Hook closure'],
//     specifications: { Material: '100% Polyester', Length: 'Mid-thigh', Care: 'Dry Clean' },
//     relatedProducts: ['7', '9', '25'],
//   },
//   {
//     id: '25',
//     name: 'Trench Coat',
//     price: 179.99,
//     originalPrice: 219.99,
//     image: 'https://images.unsplash.com/photo-1544027993-7ad4f6a7a3a0?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1544027993-7ad4f6a7a3a0?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 650,
//     isWishlisted: false,
//     category: 'womens-outerwear',
//     material: 'cotton',
//     description: 'A classic cotton trench coat, ideal for transitional weather.',
//     inStock: true,
//     features: ['Cotton blend', 'Double-breasted', 'Belted waist', 'Water-resistant'],
//     specifications: { Material: '70% Cotton, 30% Polyester', Length: 'Knee-length', Care: 'Machine Wash' },
//     relatedProducts: ['7', '24', '26'],
//   },

//   // womens-activewear
//   {
//     id: '26',
//     name: 'Sports Bra',
//     price: 39.99,
//     originalPrice: 49.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 780,
//     isWishlisted: true,
//     category: 'womens-activewear',
//     material: 'polyester',
//     description: 'A supportive sports bra, perfect for high-intensity workouts.',
//     inStock: true,
//     features: ['Moisture-wicking fabric', 'Medium support', 'Adjustable straps', 'Breathable mesh'],
//     specifications: { Material: '85% Polyester, 15% Spandex', Fit: 'Fitted', Care: 'Machine Wash' },
//     relatedProducts: ['19', '27', '30'],
//   },
//   {
//     id: '27',
//     name: 'Running Leggings',
//     price: 59.99,
//     originalPrice: 79.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 920,
//     isWishlisted: false,
//     category: 'womens-activewear',
//     material: 'polyester',
//     description: 'High-performance running leggings with a comfortable stretch fit.',
//     inStock: true,
//     features: ['Stretch polyester', 'High-waisted', 'Side phone pocket', 'Reflective details'],
//     specifications: { Material: '80% Polyester, 20% Spandex', Fit: 'Fitted', Care: 'Machine Wash' },
//     relatedProducts: ['19', '26', '30'],
//   },

//   // mens-shirts
//   {
//     id: '28',
//     name: 'Oxford Dress Shirt',
//     price: 69.99,
//     originalPrice: 89.99,
//     image: 'https://images.unsplash.com/photo-1596755032439-0b297c8a371e?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1596755032439-0b297c8a371e?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 1100,
//     isWishlisted: true,
//     category: 'Dress Shirts',
//     material: 'cotton',
//     description: 'A crisp oxford dress shirt, perfect for formal and business settings.',
//     inStock: true,
//     features: ['100% Cotton', 'Button-down collar', 'Slim fit', 'Non-iron'],
//     specifications: { Material: '100% Cotton', Fit: 'Slim', Care: 'Machine Wash' },
//     relatedProducts: ['9', '29', '33'],
//   },
//   {
//     id: '29',
//     name: 'Polo Shirt',
//     price: 49.99,
//     originalPrice: 59.99,
//     image: 'https://images.unsplash.com/photo-1596755032439-0b297c8a371e?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1596755032439-0b297c8a371e?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 850,
//     isWishlisted: false,
//     category: 'Polo Shirts',
//     material: 'cotton',
//     description: 'A classic cotton polo shirt, ideal for casual and semi-formal occasions.',
//     inStock: true,
//     features: ['100% Cotton', 'Three-button placket', 'Ribbed collar', 'Regular fit'],
//     specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['28', '30', '33'],
//   },

//   // mens-t-shirts
//   {
//     id: '30',
//     name: 'Graphic Tee',
//     price: 34.99,
//     originalPrice: 44.99,
//     image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 1200,
//     isWishlisted: true,
//     category: 'Graphic Tees',
//     material: 'cotton',
//     description: 'A trendy graphic t-shirt with a bold print, perfect for casual wear.',
//     inStock: true,
//     features: ['100% Cotton', 'Crew neck', 'Printed design', 'Pre-shrunk'],
//     specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['12', '18', '31'],
//   },
//   {
//     id: '31',
//     name: 'V-Neck Tee',
//     price: 29.99,
//     originalPrice: 39.99,
//     image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=600&fit=crop',
//     ],
//     rating: 4.5,
//     reviews: 980,
//     isWishlisted: false,
//     category: 'V-Neck',
//     material: 'cotton',
//     description: 'A comfortable V-neck t-shirt, great for layering or standalone wear.',
//     inStock: true,
//     features: ['100% Cotton', 'V-neck', 'Short sleeves', 'Soft fabric'],
//     specifications: { Material: '100% Cotton', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['12', '30', '32'],
//   },

//   // mens-jeans
//   {
//     id: '32',
//     name: 'Slim Fit Jeans',
//     price: 79.99,
//     originalPrice: 99.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 1050,
//     isWishlisted: true,
//     category: 'mens-jeans',
//     material: 'denim',
//     description: 'Classic slim fit jeans, perfect for everyday wear.',
//     inStock: true,
//     features: ['100% Cotton Denim', 'Slim fit', 'Five-pocket style', 'Stretch fabric'],
//     specifications: { Material: '98% Cotton, 2% Spandex', Fit: 'Slim', Care: 'Machine Wash' },
//     relatedProducts: ['6', '33', '34'],
//   },
//   {
//     id: '33',
//     name: 'Distressed Jeans',
//     price: 89.99,
//     originalPrice: 109.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 870,
//     isWishlisted: false,
//     category: 'mens-jeans',
//     material: 'denim',
//     description: 'Trendy distressed jeans with a relaxed fit, ideal for casual looks.',
//     inStock: true,
//     features: ['100% Cotton Denim', 'Relaxed fit', 'Distressed details', 'Five-pocket style'],
//     specifications: { Material: '100% Cotton', Fit: 'Relaxed', Care: 'Machine Wash' },
//     relatedProducts: ['6', '32', '34'],
//   },

//   // mens-jackets
//   {
//     id: '34',
//     name: 'Bomber Jacket',
//     price: 129.99,
//     originalPrice: 159.99,
//     image: 'https://images.unsplash.com/photo-1525171254930-643fc83d3c66?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1525171254930-643fc83d3c66?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 690,
//     isWishlisted: true,
//     category: 'mens-jackets',
//     material: 'polyester',
//     description: 'A stylish bomber jacket, perfect for casual and transitional weather.',
//     inStock: true,
//     features: ['Polyester shell', 'Ribbed cuffs', 'Zip front', 'Side pockets'],
//     specifications: { Material: '100% Polyester', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['6', '32', '35'],
//   },
//   {
//     id: '35',
//     name: 'Leather Jacket',
//     price: 199.99,
//     originalPrice: 249.99,
//     image: 'https://images.unsplash.com/photo-1525171254930-643fc83d3c66?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1525171254930-643fc83d3c66?w=600&h=600&fit=crop',
//     ],
//     rating: 4.9,
//     reviews: 520,
//     isWishlisted: false,
//     category: 'mens-jackets',
//     material: 'leather',
//     description: 'A premium leather jacket, ideal for a bold, timeless look.',
//     inStock: true,
//     features: ['Genuine leather', 'Zip front', 'Side pockets', 'Lined interior'],
//     specifications: { Material: 'Genuine Leather', Fit: 'Regular', Care: 'Leather Cleaner' },
//     relatedProducts: ['10', '34', '36'],
//   },

//   // mens-suits
//   {
//     id: '36',
//     name: 'Slim Fit Suit',
//     price: 299.99,
//     originalPrice: 399.99,
//     image: 'https://images.unsplash.com/photo-1598033129183-c4f50c6cb6c8?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1598033129183-c4f50c6cb6c8?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 450,
//     isWishlisted: true,
//     category: 'mens-suits',
//     material: 'wool',
//     description: 'A sleek slim fit suit, perfect for formal occasions and business meetings.',
//     inStock: true,
//     features: ['Wool blend', 'Single-breasted', 'Notched lapel', 'Two-button closure'],
//     specifications: { Material: '80% Wool, 20% Polyester', Fit: 'Slim', Care: 'Dry Clean' },
//     relatedProducts: ['2', '28', '37'],
//   },
//   {
//     id: '37',
//     name: 'Tuxedo',
//     price: 349.99,
//     originalPrice: 449.99,
//     image: 'https://images.unsplash.com/photo-1598033129183-c4f50c6cb6c8?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1598033129183-c4f50c6cb6c8?w=600&h=600&fit=crop',
//     ],
//     rating: 4.9,
//     reviews: 380,
//     isWishlisted: false,
//     category: 'mens-suits',
//     material: 'wool',
//     description: 'A classic black tuxedo, ideal for weddings and black-tie events.',
//     inStock: true,
//     features: ['Wool blend', 'Satin lapels', 'Single-breasted', 'Side vents'],
//     specifications: { Material: '80% Wool, 20% Polyester', Fit: 'Regular', Care: 'Dry Clean' },
//     relatedProducts: ['2', '28', '36'],
//   },

//   // mens-activewear
//   {
//     id: '38',
//     name: 'Performance Hoodie',
//     price: 59.99,
//     originalPrice: 79.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 870,
//     isWishlisted: true,
//     category: 'mens-activewear',
//     material: 'polyester',
//     description: 'A lightweight performance hoodie, perfect for workouts and outdoor activities.',
//     inStock: true,
//     features: ['Moisture-wicking fabric', 'Thumbhole cuffs', 'Zip pocket', 'Breathable mesh'],
//     specifications: { Material: '85% Polyester, 15% Spandex', Fit: 'Regular', Care: 'Machine Wash' },
//     relatedProducts: ['26', '27', '39'],
//   },
//   {
//     id: '39',
//     name: 'Running Shorts',
//     price: 39.99,
//     originalPrice: 49.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 760,
//     isWishlisted: false,
//     category: 'mens-activewear',
//     material: 'polyester',
//     description: 'Breathable running shorts with a comfortable fit, ideal for active lifestyles.',
//     inStock: true,
//     features: ['Polyester blend', 'Elastic waistband', 'Side pockets', 'Reflective logo'],
//     specifications: { Material: '90% Polyester, 10% Spandex', Length: '7 inches', Care: 'Machine Wash' },
//     relatedProducts: ['26', '38', '39'],
//   },

//   // bags
//   {
//     id: '40',
//     name: 'Structured Tote Bag',
//     price: 299.99,
//     originalPrice: 349.99,
//     image: 'https://images.unsplash.com/photo-1590451999253-6113b6473b64?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1590451999253-6113b6473b64?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 590,
//     isWishlisted: true,
//     category: 'Tote Bags',
//     material: 'leather',
//     description: 'A sophisticated leather tote bag, perfect for work or weekend outings.',
//     inStock: true,
//     features: ['Genuine leather', 'Top zip closure', 'Interior pockets', 'Detachable strap'],
//     specifications: { Material: 'Italian Leather', Dimensions: '16" W x 12" H x 6" D', Color: 'Brown' },
//     relatedProducts: ['3', '10', '41'],
//   },
//   {
//     id: '41',
//     name: 'Canvas Backpack',
//     price: 99.99,
//     originalPrice: 129.99,
//     image: 'https://images.unsplash.com/photo-1553062407-98eeb68c6a62?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1553062407-98eeb68c6a62?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 720,
//     isWishlisted: false,
//     category: 'Backpacks',
//     material: 'canvas',
//     description: 'A durable canvas backpack, ideal for daily commutes or travel.',
//     inStock: true,
//     features: ['Canvas material', 'Padded laptop sleeve', 'Multiple compartments', 'Adjustable straps'],
//     specifications: { Material: 'Canvas', Capacity: '25L', Dimensions: '18" H x 12" W x 6" D' },
//     relatedProducts: ['11', '40', '42'],
//   },

//   // shoes
//   {
//     id: '42',
//     name: 'Leather Loafers',
//     price: 129.99,
//     originalPrice: 159.99,
//     image: 'https://images.unsplash.com/photo-1516478177764-9fe567e9777d?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1516478177764-9fe567e9777d?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 680,
//     isWishlisted: true,
//     category: 'shoes',
//     material: 'leather',
//     description: 'Classic leather loafers, perfect for both casual and formal occasions.',
//     inStock: true,
//     features: ['Genuine leather', 'Slip-on design', 'Cushioned insole', 'Durable sole'],
//     specifications: { Material: 'Leather', Outsole: 'Rubber', Color: 'Black' },
//     relatedProducts: ['8', '11', '43'],
//   },
//   {
//     id: '43',
//     name: 'High Heels',
//     price: 99.99,
//     originalPrice: 129.99,
//     image: 'https://images.unsplash.com/photo-1543168256-418811576f69?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1543168256-418811576f69?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 540,
//     isWishlisted: false,
//     category: 'Heels',
//     material: 'suede',
//     description: 'Elegant suede high heels, perfect for evening wear or special events.',
//     inStock: true,
//     features: ['Suede upper', '3-inch heel', 'Padded insole', 'Pointed toe'],
//     specifications: { Material: 'Suede', HeelHeight: '3 inches', Care: 'Suede Cleaner' },
//     relatedProducts: ['8', '42', '44'],
//   },

//   // jewelery
//   {
//     id: '44',
//     name: 'Silver Necklace',
//     price: 149.99,
//     originalPrice: 179.99,
//     image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 920,
//     isWishlisted: true,
//     category: 'Necklaces',
//     material: 'silver',
//     description: 'A delicate silver necklace with a minimalist pendant, perfect for daily wear.',
//     inStock: true,
//     features: ['925 Sterling Silver', 'Adjustable chain', 'Minimalist pendant', 'Hypoallergenic'],
//     specifications: { Material: '925 Sterling Silver', ChainLength: '16-18 inches', Weight: '8g' },
//     relatedProducts: ['5', '45', '46'],
//   },
//   {
//     id: '45',
//     name: 'Diamond Stud Earrings',
//     price: 299.99,
//     originalPrice: 349.99,
//     image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop',
//     ],
//     rating: 4.9,
//     reviews: 670,
//     isWishlisted: false,
//     category: 'Earrings',
//     material: 'platinum',
//     description: 'Elegant diamond stud earrings, perfect for adding sparkle to any outfit.',
//     inStock: true,
//     features: ['Platinum setting', '0.5 Carat diamonds', 'Secure clasp', 'Certified stones'],
//     specifications: { Material: '950 Platinum', Stone: '0.5 Carat Diamond', Weight: '3g' },
//     relatedProducts: ['44', '46', '47'],
//   },
//   {
//     id: '46',
//     name: 'Gold Charm Bracelet',
//     price: 199.99,
//     originalPrice: 249.99,
//     image: 'https://images.unsplash.com/photo-1611652022417-a553e1e3b0c8?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1611652022417-a553e1e3b0c8?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 780,
//     isWishlisted: true,
//     category: 'Bracelets',
//     material: 'gold',
//     description: 'A charming gold bracelet with customizable charms, perfect for gifting.',
//     inStock: true,
//     features: ['14K Gold Plated', 'Lobster clasp', 'Three starter charms', 'Adjustable length'],
//     specifications: { Material: '14K Gold Plated', Length: '7-8 inches', Weight: '12g' },
//     relatedProducts: ['44', '45', '47'],
//   },
//   {
//     id: '47',
//     name: 'Sapphire Ring',
//     price: 499.99,
//     originalPrice: 599.99,
//     image: 'https://images.unsplash.com/photo-1598561042797-2cf36e77a494?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1598561042797-2cf36e77a494?w=600&h=600&fit=crop',
//     ],
//     rating: 4.9,
//     reviews: 560,
//     isWishlisted: false,
//     category: 'Rings',
//     material: 'platinum',
//     description: 'A stunning sapphire ring with a platinum band, ideal for special occasions.',
//     inStock: true,
//     features: ['950 Platinum', '1.5 Carat Sapphire', 'Diamond accents', 'Certified stone'],
//     specifications: { Material: '950 Platinum', Stone: '1.5 Carat Sapphire', RingSize: '7 (US)' },
//     relatedProducts: ['44', '45', '46'],
//   },

//   // watches
//   {
//     id: '48',
//     name: 'Stainless Steel Watch',
//     price: 249.99,
//     originalPrice: 299.99,
//     image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&h=600&fit=crop',
//     ],
//     rating: 4.8,
//     reviews: 890,
//     isWishlisted: true,
//     category: 'watches',
//     material: 'stainless-steel',
//     description: 'A sleek stainless steel watch with a minimalist design, perfect for daily wear.',
//     inStock: true,
//     features: ['Swiss Quartz Movement', 'Stainless steel case', 'Water-resistant', 'Date window'],
//     specifications: { Material: 'Stainless Steel', Movement: 'Quartz', WaterResistance: '50m' },
//     relatedProducts: ['5', '44', '49'],
//   },
//   {
//     id: '49',
//     name: 'Leather Strap Watch',
//     price: 199.99,
//     originalPrice: 249.99,
//     image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 720,
//     isWishlisted: false,
//     category: 'watches',
//     material: 'leather',
//     description: 'A classic watch with a genuine leather strap, ideal for formal occasions.',
//     inStock: true,
//     features: ['Swiss Quartz Movement', 'Leather strap', 'Water-resistant', 'Analog display'],
//     specifications: { Material: 'Leather Strap, Stainless Steel', Movement: 'Quartz', WaterResistance: '30m' },
//     relatedProducts: ['5', '48', '50'],
//   },

//   // sunglasses
//   {
//     id: '50',
//     name: 'Aviator Sunglasses',
//     price: 99.99,
//     originalPrice: 129.99,
//     image: 'https://images.unsplash.com/photo-1511497580566-2c2d9962c46f?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1511497580566-2c2d9962c46f?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 650,
//     isWishlisted: true,
//     category: 'sunglasses',
//     material: 'metal',
//     description: 'Classic aviator sunglasses with polarized lenses, perfect for sunny days.',
//     inStock: true,
//     features: ['Polarized lenses', 'Metal frame', 'UV protection', 'Adjustable nose pads'],
//     specifications: { Material: 'Metal', Lens: 'Polarized', Protection: 'UV400' },
//     relatedProducts: ['51', '52', '53'],
//   },
//   {
//     id: '51',
//     name: 'Cat-Eye Sunglasses',
//     price: 89.99,
//     originalPrice: 109.99,
//     image: 'https://images.unsplash.com/photo-1511497580566-2c2d9962c46f?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1511497580566-2c2d9962c46f?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 580,
//     isWishlisted: false,
//     category: 'sunglasses',
//     material: 'plastic',
//     description: 'Trendy cat-eye sunglasses with a bold frame, ideal for fashion-forward looks.',
//     inStock: true,
//     features: ['Plastic frame', 'Polarized lenses', 'UV protection', 'Lightweight'],
//     specifications: { Material: 'Plastic', Lens: 'Polarized', Protection: 'UV400' },
//     relatedProducts: ['50', '52', '53'],
//   },

//   // hats
//   {
//     id: '52',
//     name: 'Wool Fedora',
//     price: 69.99,
//     originalPrice: 89.99,
//     image: 'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 470,
//     isWishlisted: true,
//     category: 'hats',
//     material: 'wool',
//     description: 'A stylish wool fedora, perfect for adding sophistication to any outfit.',
//     inStock: true,
//     features: ['Wool felt', 'Pinched crown', 'Wide brim', 'Adjustable band'],
//     specifications: { Material: '100% Wool', BrimWidth: '2.5 inches', Care: 'Spot Clean' },
//     relatedProducts: ['50', '51', '53'],
//   },
//   {
//     id: '53',
//     name: 'Baseball Cap',
//     price: 29.99,
//     originalPrice: 39.99,
//     image: 'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=600&h=600&fit=crop',
//     ],
//     rating: 4.5,
//     reviews: 820,
//     isWishlisted: false,
//     category: 'hats',
//     material: 'cotton',
//     description: 'A classic cotton baseball cap, ideal for casual and sporty looks.',
//     inStock: true,
//     features: ['100% Cotton', 'Adjustable strap', 'Curved brim', 'Embroidered logo'],
//     specifications: { Material: '100% Cotton', Fit: 'Adjustable', Care: 'Machine Wash' },
//     relatedProducts: ['50', '51', '52'],
//   },

//   // Girls Clothing
//   {
//     id: '54',
//     name: 'Girls Floral Dress',
//     price: 39.99,
//     originalPrice: 49.99,
//     image: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1572804013427-4d7ca7268211?w=600&h=600&fit=crop',
//     ],
//     rating: 4.7,
//     reviews: 650,
//     isWishlisted: true,
//     category: 'Girls Clothing',
//     material: 'cotton',
//     description: 'A charming floral dress for girls, perfect for playdates or parties.',
//     inStock: true,
//     features: ['100% Cotton', 'A-line shape', 'Back zipper', 'Breathable fabric'],
//     specifications: { Material: '100% Cotton', Length: 'Knee-length', Care: 'Machine Wash' },
//     relatedProducts: ['55', '56', '57'],
//   },
//   {
//     id: '55',
//     name: 'Girls Denim Skirt',
//     price: 29.99,
//     originalPrice: 39.99,
//     image: 'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=400&h=500&fit=crop&crop=center',
//     images: [
//       'https://images.unsplash.com/photo-1591195853828-11ae3c3b3b4b?w=600&h=600&fit=crop',
//     ],
//     rating: 4.6,
//     reviews: 520,
//     isWishlisted: false,
//     category: 'Girls Clothing',
//     material: 'denim',
//     description: 'A cute denim skirt for girls, ideal for casual wear.',
//     inStock: true,
//      features: ['100% Cotton', 'A-line shape', 'Back zipper', 'Breathable fabric'],
//     specifications: { Material: '100% Cotton', Length: 'Knee-length', Care: 'Machine Wash' },
//     relatedProducts: ['55', '56', '57'],
//   },
// ]